name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e417b46207259264a7747140217379c1e5863d92162a11dab82be37590854353"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
