name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a60af994faf21a4540baf6892b78ba477ed63db9d196e561764c54f3900017bb"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
