name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd5d2058db01ceff6a06c805551e32356282272b1c8db9e95eb1b5ed35ad1f51"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
