name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b780481550a8ae5cc8358cbc7cd08002e7c186044872096ff7095122d1d9af7"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
