name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0835f2538af91ffbbd9e7cc2a89910612244403adb6de4940f79e78759c70217"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
