name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26bdd3990fa60afdc0fc981705130b941ecc48534c160fbdc65025b1a2a579dc"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
