name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c787aa7335318d4ea4293f8c1886e56955433c0996fbd64179e72517d7865e98"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
