name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bf2e6231f62c547b5c2c982abb07c70682dbe0974df46212eea3e04b9ecdb7e"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
