name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32e27f5d44228b46c736df34d359e4a594e223bf726033a72c13d38c7f16ab83"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
