name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a0704a1713dcaf14d3265209bb8710fcd11f4ec073e35b70447d8af598fd53e"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
