name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c780ee4bbca8b9fb3ee4a6fe10b2ea2438d53718124aeaa901ab336900ebcb9a"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
