name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6749e0f76e9e81a1b6418ba9f24f07d6612f1ef7a8215426b96d2914f870c1e1"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
