name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c95c5c5d486bee379c6ba1693e189549dd6be8526e28d9a3df28b93b91a3b7b9"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
