name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0436b0a7d8f66e4ce0587fdb1f23c243be517e8706f4de5769256aed61bde592"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
