name = "Les enfants sans mains"
author = "Panderine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b12e580d5529700f857e77742ded4baa55ae8d474c6b4adfaa890701233b4db"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
