name = "AttributeFix"
filename = "AttributeFix-Forge-1.18.1-13.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/619/AttributeFix-Forge-1.18.1-13.0.5.jar"
hash-format = "sha1"
hash = "1e219bcf01fee3771df04a95d2ac03bd80519072"

[update]
[update.curseforge]
file-id = 3615619
project-id = 280510
