name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.1-1.3.2-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/205/betterbiomeblend-1.18.1-1.3.2-forge.jar"
hash-format = "sha1"
hash = "ab22bff1d2cbfdd929c264ddf6c27d2dab078840"

[update]
[update.curseforge]
file-id = 3615205
project-id = 446253
