name = "Better Advancements"
filename = "BetterAdvancements-1.18.1-0.1.2.122.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/636/BetterAdvancements-1.18.1-0.1.2.122.jar"
hash-format = "sha1"
hash = "c390d07757b53a2ebb6e3bbde7f1ad08f0e4eda0"

[update]
[update.curseforge]
file-id = 3575636
project-id = 272515
