name = "Buddycards Expansions"
filename = "BuddycardsExpansions-1.18.1-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/893/BuddycardsExpansions-1.18.1-1.0.4.jar"
hash-format = "sha1"
hash = "d5ad550f45ee282642cd3b37b185bb23a3f8a414"

[update]
[update.curseforge]
file-id = 3669893
project-id = 568127
