name = "CleanCut"
filename = "cleancut-mc1.18-3.0-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/929/cleancut-mc1.18-3.0-forge.jar"
hash-format = "sha1"
hash = "367330ab16111c7e2a7c2b67cc4305211deb9d65"

[update]
[update.curseforge]
file-id = 3542929
project-id = 392805
