name = "Convenient Curios Container"
filename = "convenientcurioscontainer-1.1-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/560/convenientcurioscontainer-1.1-1.18.jar"
hash-format = "sha1"
hash = "142aeaa8c9ce14f978ed7422807fe7b623d9a4ea"

[update]
[update.curseforge]
file-id = 3545560
project-id = 544033
