name = "Corpse"
filename = "corpse-1.18.1-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/69/corpse-1.18.1-1.0.5.jar"
hash-format = "sha1"
hash = "0e8c0f2c59be2fda5ec7a8cea5105d53a9323400"

[update]
[update.curseforge]
file-id = 3666069
project-id = 316582
