name = "Dimensional Pockets II"
filename = "dimensionalpocketsii-1.18.1-5.1.3.10-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/288/dimensionalpocketsii-1.18.1-5.1.3.10-universal.jar"
hash-format = "sha1"
hash = "d5b6f5751ac56c6ccc23b5f4486670499b14660f"

[update]
[update.curseforge]
file-id = 3639288
project-id = 282573
