name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Forge-1.18.1-9.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/901/EnchantmentDescriptions-Forge-1.18.1-9.0.13.jar"
hash-format = "sha1"
hash = "221c8e2cc97e50cfe3aee2e52d71c76619a29c29"

[update]
[update.curseforge]
file-id = 3636901
project-id = 250419
