name = "EnderTanks"
filename = "endertanks-1.18-1.11.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/617/endertanks-1.18-1.11.3.jar"
hash-format = "sha1"
hash = "5d60ee3a788c7521dd371449209dfce3af728121"

[update]
[update.curseforge]
file-id = 3681617
project-id = 59613
