name = "EnderChests"
filename = "enderchests-1.18-1.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/610/enderchests-1.18-1.9.2.jar"
hash-format = "sha1"
hash = "453f945f7e8dd703c294186006362acca193ce42"

[update]
[update.curseforge]
file-id = 3681610
project-id = 363535
