name = "Entangled"
filename = "entangled-1.3.10-mc1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/974/entangled-1.3.10-mc1.18.jar"
hash-format = "sha1"
hash = "8bdff35b331014c546a80893cd12eeb3761c7362"

[update]
[update.curseforge]
file-id = 3543974
project-id = 301034
