name = "Falling Leaves (Forge)"
filename = "Fallingleaves-1.18.1-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3620/401/Fallingleaves-1.18.1-1.3.1.jar"
hash-format = "sha1"
hash = "5bcd1a1ea1a93d06127724a65bf512687778cf53"

[update]
[update.curseforge]
file-id = 3620401
project-id = 463155
