name = "Farming for Blockheads"
filename = "farmingforblockheads-forge-1.18.1-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/204/farmingforblockheads-forge-1.18.1-9.0.3.jar"
hash-format = "sha1"
hash = "a0ea625dc4eaf8e323b6d006ff3d6cb2e3f4117c"

[update]
[update.curseforge]
file-id = 3606204
project-id = 261924
