name = "Fast Leaf Decay"
filename = "FastLeafDecay-27.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/415/FastLeafDecay-27.2.jar"
hash-format = "sha1"
hash = "d2cf210146fc4f2f2120b3417afacc34eb38d700"

[update]
[update.curseforge]
file-id = 3590415
project-id = 230976
