name = "Guard Villagers"
filename = "guardvillagers-1.18.1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/222/guardvillagers-1.18.1.4.0.jar"
hash-format = "sha1"
hash = "ba618a47b011881195ebcb0077fe5474110aef98"

[update]
[update.curseforge]
file-id = 3548222
project-id = 360203
