name = "Just Enough Items (JEI)"
filename = "jei-1.18.1-9.4.1.172.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/162/jei-1.18.1-9.4.1.172.jar"
hash-format = "sha1"
hash = "00a4c111086c43c799f2f13d2e8c86216dad8232"

[update]
[update.curseforge]
file-id = 3723162
project-id = 238222
