name = "Macaw's Lights and Lamps"
filename = "mcw-lights-1.0.3-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/39/mcw-lights-1.0.3-mc1.18.1.jar"
hash-format = "sha1"
hash = "7f36d3e14115364f910571de095391ae0879361e"

[update]
[update.curseforge]
file-id = 3683039
project-id = 502372
