name = "Multi-Piston"
filename = "multi-piston-1.18-1.2.2-ALPHA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/720/multi-piston-1.18-1.2.2-ALPHA.jar"
hash-format = "sha1"
hash = "29a6ff6549b56a8d0da936e1c6680f27a453ed36"

[update]
[update.curseforge]
file-id = 3543720
project-id = 303278
