name = "Mystical Agriculture"
filename = "MysticalAgriculture-1.18.1-5.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/812/MysticalAgriculture-1.18.1-5.0.3.jar"
hash-format = "sha1"
hash = "c2884784277990286d5e743ee5dfa94ef05cc154"

[update]
[update.curseforge]
file-id = 3645812
project-id = 246640
