name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.3.0+1.18-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/304/ninjaphenix-container-library-1.3.0+1.18-forge.jar"
hash-format = "sha1"
hash = "99c3a435cd2a97715cdec904600c67aba47b84a7"

[update]
[update.curseforge]
file-id = 3649304
project-id = 530668
