name = "Oculus"
filename = "oculus-mc1.18.1-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/792/oculus-mc1.18.1-1.2.1.jar"
hash-format = "sha1"
hash = "b75320ca091ee4160751fbef7bc831fa743411fe"

[update]
[update.curseforge]
file-id = 3654792
project-id = 581495

[option]
optional = true
