name = "PneumaticCraft: Repressurized"
filename = "pneumaticcraft-repressurized-1.18.1-3.0.0-53.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/737/pneumaticcraft-repressurized-1.18.1-3.0.0-53.jar"
hash-format = "sha1"
hash = "e1012bf3ca902dce45ae32c1b68cc551d96dcd12"

[update]
[update.curseforge]
file-id = 3680737
project-id = 281849
