name = "Redstone Pen"
filename = "redstonepen-1.18.1-1.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3714/78/redstonepen-1.18.1-1.0.9.jar"
hash-format = "sha1"
hash = "0ccc2c6b0b024440062545c42ce6e8cfcbf792ac"

[update]
[update.curseforge]
file-id = 3714078
project-id = 461710
