name = "RFTools Builder"
filename = "rftoolsbuilder-1.18-4.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/833/rftoolsbuilder-1.18-4.0.7.jar"
hash-format = "sha1"
hash = "5bab707577f3460e3153661d9f23bb91b6c2a05d"

[update]
[update.curseforge]
file-id = 3665833
project-id = 347706
