name = "RFTools Dimensions"
filename = "rftoolsdim-1.18-8.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/682/rftoolsdim-1.18-8.0.3.jar"
hash-format = "sha1"
hash = "94463e2a606744015fa9b7e6cb4c006d5422c6f9"

[update]
[update.curseforge]
file-id = 3645682
project-id = 240950
