name = "RFTools Utility"
filename = "rftoolsutility-1.18-4.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/830/rftoolsutility-1.18-4.0.10.jar"
hash-format = "sha1"
hash = "470d23802f2eb5f1931e36a74676c1345142f24f"

[update]
[update.curseforge]
file-id = 3665830
project-id = 342466
