name = "ShetiPhianCore"
filename = "shetiphiancore-1.18-3.10.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/606/shetiphiancore-1.18-3.10.4.jar"
hash-format = "sha1"
hash = "3c1de6b6c2c8b5824a0ba594fb0ee12fbf5862a9"

[update]
[update.curseforge]
file-id = 3681606
project-id = 71738
