name = "Tetra"
filename = "tetra-1.18.1-4.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3711/77/tetra-1.18.1-4.8.1.jar"
hash-format = "sha1"
hash = "3b93c178f4a02820905df1fa907eb4475e56e46c"

[update]
[update.curseforge]
file-id = 3711077
project-id = 289712
