name = "Tool Belt"
filename = "ToolBelt-1.18-1.18.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/183/ToolBelt-1.18-1.18.0.jar"
hash-format = "sha1"
hash = "e53af729c88b0a9d2f3ced3cf68c79a3427d9449"

[update]
[update.curseforge]
file-id = 3548183
project-id = 260262
